# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: creativesizzle.redirect::lang.redirect.category

# Model Form Field configuration
form: $/creativesizzle/redirect/models/category/fields.yaml

# Model Class name
modelClass: CreativeSizzle\Redirect\Models\Category

# Default redirect location
defaultRedirect: creativesizzle/redirect/categories

# Create page
create:
    title: creativesizzle.redirect::lang.title.create_category
    redirect: creativesizzle/redirect/categories/update/:id
    redirectClose: creativesizzle/redirect/categories

# Update page
update:
    title: creativesizzle.redirect::lang.title.edit_category
    redirect: creativesizzle/redirect/categories
    redirectClose: creativesizzle/redirect/categories
