# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: creativesizzle.redirect::lang.buttons.reorder_redirects

# Attribute name
nameFrom: from_url

# Model Class name
modelClass: CreativeSizzle\Redirect\Models\Redirect

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
