# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: creativesizzle.redirect::lang.redirect.redirect

# Model Form Field configuration
form: $/creativesizzle/redirect/models/redirect/fields.yaml

# Model Class name
modelClass: CreativeSizzle\Redirect\Models\Redirect

# Default redirect location
defaultRedirect: creativesizzle/redirect/redirects

# Create page
create:
    title: creativesizzle.redirect::lang.title.create_redirect
    redirect: creativesizzle/redirect/redirects/update/:id
    redirectClose: creativesizzle/redirect/redirects

# Update page
update:
    title: creativesizzle.redirect::lang.title.edit_redirect
    redirect: creativesizzle/redirect/redirects
    redirectClose: creativesizzle/redirect/redirects
