# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: creativesizzle.redirect::lang.title.import
    modelClass: CreativeSizzle\Redirect\Models\RedirectImport
    list: $/creativesizzle/redirect/models/redirectimport/columns.yaml
    redirect: creativesizzle/redirect/redirects
export:
    title: creativesizzle.redirect::lang.title.export
    modelClass: CreativeSizzle\Redirect\Models\RedirectExport
    list: $/creativesizzle/redirect/models/redirectexport/columns.yaml
    redirect: creativesizzle/redirect/redirects
    filename: redirects.csv
