name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpUnitTests:
    runs-on: ubuntu-latest

    name: Unit Tests / PHP ${{ matrix.phpVersions }}

    strategy:
      max-parallel: 6
      matrix:
        phpVersions: ['8.0', '8.1']
      fail-fast: false

    env:
      phpExtensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
      winterCmsRelease: develop

    steps:
      - name: Checkout Changes
        uses: actions/checkout@v2
        with:
          path: redirect-plugin

      - name: Install PHP and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersions }}
          extensions: ${{ env.phpExtensions }}
          tools: composer:v2

      - name: Install Winter CMS
        run: |
          curl -L https://github.com/wintercms/winter/archive/${{ env.winterCmsRelease }}.zip -o ${{ env.winterCmsRelease }}.zip -s
          unzip ${{ env.winterCmsRelease }}.zip
          rm ${{ env.winterCmsRelease }}.zip
          shopt -s dotglob
          mv winter-${{ env.winterCmsRelease }}/* ./
          rmdir winter-${{ env.winterCmsRelease }}
          shopt -u dotglob
          mkdir -p plugins/creativesizzle
          mv redirect-plugin plugins/creativesizzle/redirect
          composer config --json --merge extra.merge-plugin.include '["plugins/creativesizzle/redirect/composer.json"]'

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Run linting
        run: ./vendor/bin/parallel-lint plugins/creativesizzle/redirect

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          php artisan winter:test -p CreativeSizzle.Redirect
